# Generated by Django 2.2.12 on 2021-10-25 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CountryDataCovid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('infected', models.BigIntegerField()),
                ('dead', models.BigIntegerField()),
                ('uci', models.BigIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_data_covid_id_country', to='dashboard.Country', verbose_name='country')),
            ],
        ),
    ]
